### ISSUE TITLE
Themes should be able to access /usr/share/backgrounds

### ISSUE THREAD

**Issue by Aakodal** [JezerM/web-greeter#50]
## Environment
- OS: EndeavourOS (Arch based)
- web-greeter version: 3.5.0

## Description of feature
With Antergos' web greeter, themes could access /usr/share/backgrounds, and thus suggest different backgrounds for themes that allow it (such as Litarvan's). However, it is no longer the case, according to the docs (and experience).
It would be great to see that back.

**Comment by JezerM** [comment]
It is possible, themes are allowed to access `/usr/share/backgrounds` as long as the `background_images_dir` property in `/etc/lightdm/web-greeter.yml` is set to `/usr/share/backgrounds` (which is the default):

```yaml
# /etc/lightdm/web-greeter.yml

branding:
    background_images_dir: /usr/share/backgrounds
```
